name = "crms-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "crms-db"
database_id = "1e9c3b4c-8327-41f9-a02c-76367476214c"
migrations_dir = "../../packages/db/migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "ce6d512002fd41f28e7d00f17b56161a"

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "crms-email-queue"

[[queues.consumers]]
queue = "crms-email-queue"
max_batch_size = 10
max_batch_timeout = 5

[vars]
ENVIRONMENT = "production"
APP_URL = "https://it.audydental.com"
PUBLIC_URL = "https://it.audydental.com/submit"
B2_ENDPOINT = "https://s3.us-east-005.backblazeb2.com"
B2_BUCKET_NAME = "crms-attachments"
B2_REGION = "us-east-005"

[dev]
port = 8787
local_protocol = "http"
